/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ContentCard: typeof import('./src/components/cards/ContentCard.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FormRenderer: typeof import('./src/components/FormRenderer.vue')['default']
    InputCard: typeof import('./src/components/cards/InputCard.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OptionsCard: typeof import('./src/components/cards/OptionsCard.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButton: typeof import('./src/components/SubmitButton.vue')['default']
    TermsDialog: typeof import('./src/components/TermsDialog.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
